### PR TITLE
Release-Version 8

### PR DESCRIPTION
**Pull request by sourabhaa**
This PR includes,
1. update screenshots
2. Regenerate POT files
3. Update README
4. Update activity version
5. Update News

### CODE REVIEW

**Comment by sourabhaa** [comment]
@chimosky @JuiP @Saumya-Mishra9129 @srevinsaju, little help needed!
To regenerate POT files, I ran this  script https://github.com/sugarlabs/sugar-tools/blob/master/activity-translations

```
--2021-07-10 18:05:21--  https://translate.sugarlabs.org/projects/recall//
Resolving translate.sugarlabs.org (translate.sugarlabs.org)... 18.27.196.33
Connecting to translate.sugarlabs.org (translate.sugarlabs.org)|18.27.196.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68056 (66K) [text/html]
Saving to: ‘index.html’

index.html                                                  100%[========================================================================================================================================>]  66.46K   122KB/s    in 0.5s    

2021-07-10 18:05:24 (122 KB/s) - ‘index.html’ saved [68056/68056]

rm: missing operand
Try 'rm --help' for more information.

```
then, I ran `python3 setup.py genpot` and got this error.
```
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    bundlebuilder.start()
  File "/usr/lib/python3/dist-packages/sugar3/activity/bundlebuilder.py", line 633, in start
    globals()['cmd_' + options.command](config, options)
  File "/usr/lib/python3/dist-packages/sugar3/activity/bundlebuilder.py", line 573, in cmd_genpot
    retcode = subprocess.call(args)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xgettext'
```
Is this because there is change in the strings or did I miss any step?

**Comment by srevinsaju** [comment]
Re, error 2: It is because you do not have `xgettext` installed on your computer, or you do not have `xgettext` on `PATH`.
Re, error 1: I am yet to look into why that happened.

**Comment by quozl** [comment]
"rm: missing operand" is caused by there being no empty translations to remove the second time you run it.  Try typing "rm -v" in a shell and you'll see the same thing.  It is a fault in activity-translations.  I'm low on time to fix it, and the impact is low.  Patch welcome.

**Comment by sourabhaa** [comment]
> Re, error 2: It is because you do not have `xgettext` installed on your computer, or you do not have `xgettext` on PATH.

Thanks, fixed.

If there are new strings added, does refreshing the POT files add them to POT files or is there any other procedure?

**Comment by chimosky** [comment]
@sourabhaa said;
> If there are new strings added, does refreshing the POT files add them to POT files or is there any other procedure?

Refreshing the POT file adds the new strings to the POT file of the activity which is how pootle gets its translation strings.

**Comment by chimosky** [comment]
Reviewed, thanks.

**Pull request merged**
